networks:
  gallery_network:
    driver: bridge

services:
  rabbitmq:
    image: josarichard/rabbitmq-web-stomp:arm64
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
      - 15670:15670
    networks:
      - gallery_network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - gallery_network

  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - gallery_network

  web:
    image: josarichard/flask-web:arm64
    ports:
      - 5000
    depends_on:
      - rabbitmq
      - mongodb
      - loadbalancer
    environment:
      - MONGODB_CONTAINER_NAME: mongodb
      - RABBITMQ_CONTAINER_NAME: rabbitmq
      - DB_NAME: test2
    deploy:
      replicas: 3
      endpoint_mode: vip
    networks:
      - gallery_network
    