apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
    - containerPort: 15670
    - containerPort: 15672
    - containerPort: 15674
    - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15670
    - protocol: TCP
      port: 15672
    - protocol: TCP
      port: 15674
    - protocol: TCP
      port: 5672